base:
  pkg.installed:
    - pkgs:
      - ImageMagick
      - python2-mysql
      - php-mysqlnd
      - cronie
      - fping
      - graphviz
      - ipmitool
      - jwhois
      - libvirt
      - net-snmp
      - net-snmp-utils
      - php-cli
      - php-gd
      - php-json
      - php-mcrypt
      - php-opcache
      - php-pear
      - php-posix
      - rrdtool
      - subversion
      - wget
